global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: baker-street
    metrics_path: /metrics
    static_configs:
      - targets:
          - gateway:8000
          - catalog:8000
          - checkout:8000
          - payments:8000
          - orders:8000
